
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>
	<?php include('partials/row-data-sample-tablet.html.php') ?>