<div>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
	<?php include('partials/row-data-sample-desktop.html.php') ?>
</div>