<div>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
	<?php include('partials/row-data-sample-mobile.html.php') ?>
</div>